// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaCluster":       schema_pkg_apis_litekafka_v1alpha1_KafkaCluster(ref),
		"github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaClusterSpec":   schema_pkg_apis_litekafka_v1alpha1_KafkaClusterSpec(ref),
		"github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaClusterStatus": schema_pkg_apis_litekafka_v1alpha1_KafkaClusterStatus(ref),
	}
}

func schema_pkg_apis_litekafka_v1alpha1_KafkaCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KafkaCluster is the Schema for the kafkaclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaClusterSpec", "github.com/Svimba/lite-kafka-operator/pkg/apis/litekafka/v1alpha1.KafkaClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_litekafka_v1alpha1_KafkaClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KafkaClusterSpec defines the desired state of KafkaCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_litekafka_v1alpha1_KafkaClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KafkaClusterStatus defines the observed state of KafkaCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
